POST /categories HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Content-Length: 395

{
  "title": "Category 3",
  "color": "#7946F8",
  "description": "Category 1",
  "userId": 1,
  "isActive": true
}


### '#1DD0A5',
### '#7946F8',
### '#C224E8',
### '#FBCA1D',
### '#EE4F38',
### '#33661A',
### '#EFA83E',
### '#3A4FB5',
### '#B4B4B4',
### '#5BC4FF',
### '#89D043',
### '#646464',
### '#840AA1',
### '#D2A400',
### '#FF9384',
